# Base configs
baseurl: "https://paragliding.diogo-freitas.me/"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Paragliding by Diogo Nuno Freitas"
subtitle: "See the world through my eyes!"
author: "Diogo Nuno Freitas"
header:
  title: "Paragliding"
  subtitle: "by Diogo Nuno Freitas"
footer:
  name: "Paragliding Pilot"
  bio: "Paragliding adventures through a collection of stunning images, mostly from Madeira Islands. Get ready to glide through captivating landscapes and experience the ultimate rush of freedom, all through the lens of my carefully curated image collection."
web_design: "AJ, favicon created by Freepik - Flaticon"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"},{"tag": "DateTimeOriginal", "icon": "calendar"},{"tag": "GPSLatitude"},{"tag": "GPSLongitude"}]'
social_urls:
  twitter: "https://twitter.com/DiogoNTFreitas"
  instagram: "https://www.instagram.com/dntfreitas123/"